apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetrunbasics-deployment
  labels:
    app: aspnetrunbasics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetrunbasics
  template:
    metadata:
      labels:
        app: aspnetrunbasics
    spec:
      containers:
        - name: aspnetrunbasics
          image: nmhieuit/aspnetrunbasics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ApiSettings__GatewayAddress
              value: "http://ocelotapigw-service:8010"  
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetrunbasics-service
spec:
  type: LoadBalancer
  selector:
    app: aspnetrunbasics
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 80
