apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
  labels:
    app: basketapi
    tags.datadoghq.com/env: Development
    tags.datadoghq.com/service: basketapi
    tags.datadoghq.com/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
        tags.datadoghq.com/env: Development
        tags.datadoghq.com/service: basketapi
        tags.datadoghq.com/version: v1
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: v2.32.0
    spec:
      containers:
        - name: basketapi
          image: nmhieuit/basketapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: CORECLR_ENABLE_PROFILING
              value: "true"
            - name: CORECLR_PROFILER
              value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
            - name: CORECLR_PROFILER_PATH
              value: "/opt/datadog/Datadog.Trace.ClrProfiler.Native.so"
            - name: DD_DOTNET_TRACER_HOME
              value: "/opt/datadog"
            - name: LD_PRELOAD
              value: "/opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_ENV
              value: "dev"
            - name: DD_SERVICE
              value: "catalogapi"  
            - name: DD_VERSION
              value: "v1"
            # - name: DD_PROFILING_ENABLED
            #   value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "0.5"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: GrpcSettings__DiscountUrl
              value: "http://discountgrpc-service:8003"
            - name: EventBusSettings__HostAddress
              value: "amqp://user:XPyn3sPtaiW6MZeJ@my-release-rabbitmq:5672"
            - name: CacheSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: basketdb-configmap
                    key: ConnectionString   
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
  labels:
      app: discountgrpc
spec:
  # type: LoadBalancer
  selector:
    app: basketapi
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
