apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
  labels:
    app: basketapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
        - name: basketapi
          image: nmhieuit/basketapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: GrpcSettings__DiscountUrl
              value: "http://discountgrpc-service"
            # - name: GrpcSettings__DiscountUrl
            #   valueFrom:
            #       configMapKeyRef:
            #         name: discountgrpc-configmap
            #         key: DiscountUrl
            - name: CacheSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: basketdb-configmap
                    key: ConnectionString   
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
  labels:
      app: discountgrpc
spec:
  type: LoadBalancer
  selector:
    app: basketapi
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
