apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi-deployment
  labels:
    app: catalogapi
    tags.datadoghq.com/env: Development
    tags.datadoghq.com/service: catalogapi
    tags.datadoghq.com/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
        tags.datadoghq.com/env: Development
        tags.datadoghq.com/service: catalogapi
        tags.datadoghq.com/version: v1
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/dotnet-lib.version: v2.32.0
    spec:
      containers:
        - name: catalogapi
          image: nmhieuit/catalogapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            # - name: CORECLR_ENABLE_PROFILING
            #   value: "true"
            # - name: CORECLR_PROFILER
            #   value: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
            # - name: CORECLR_PROFILER_PATH
            #   value: "/opt/datadog/Datadog.Trace.ClrProfiler.Native.so"
            # - name: DD_DOTNET_TRACER_HOME
            #   value: "/opt/datadog"
            # - name: LD_PRELOAD
            #   value: "/opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so"
            # - name: DD_PROFILING_ENABLED
            #   value: "true"
            # - name: DD_ENV
            #   value: "dev"
            # - name: DD_SERVICE
            #   value: "catalogapi"  
            # - name: DD_VERSION
            #   value: "v1"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "0.5"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  # type: LoadBalancer
  selector:
    app: catalogapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
