apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog.api-deployment
  labels:
    app: catalog.api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog.api
  template:
    metadata:
      labels:
        app: catalog.api
    spec:
      containers:
        - name: catalog.api
          image: nmhieuit/catalogapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog.api-service
spec:
  type: LoadBalancer
  selector:
    app: catalog.api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
