apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc-deployment
  labels:
    app: discountgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountgrpc
  template:
    metadata:
      labels:
        app: discountgrpc
    spec:
      containers:
        - name: discountgrpc
          image: nmhieuit/discountgrpc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: discountdb-configmap
                    key: ConnectionString   
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountgrpc-service
spec:
  selector:
    app: discountgrpc
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 80
