apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi-deployment
  labels:
    app: discountapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
        - name: discountapi
          image: nmhieuit/discountapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: basketdb-configmap
                    key: ConnectionString   
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  type: LoadBalancer
  selector:
    app: discountapi
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 80
