apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi-deployment
  labels:
    app: discountapi
    # tags.datadoghq.com/env: "dev"
    # tags.datadoghq.com/service: "discount"
    # tags.datadoghq.com/version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
      #   tags.datadoghq.com/env: "dev"
      #   tags.datadoghq.com/service: "discount"
      #   tags.datadoghq.com/version: "1"
      #   admission.datadoghq.com/enabled: "true"
      # annotations:
      #   admission.datadoghq.com/dotnet-lib.version: "v2.33.0"
    spec:
      containers:
        - name: discountapi
          image: nmhieuit/discountapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            # - name: DD_LOGS_INJECTION
            #   value: "true"
            # - name: DD_TRACE_SAMPLE_RATE
            #   value: "0.5"
            # - name: DD_RUNTIME_METRICS_ENABLED
            #   value: "true"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: discountdb-configmap
                    key: ConnectionString   
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  type: LoadBalancer
  selector:
    app: discountapi
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 80
