apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigw-deployment
  labels:
    app: ocelotapigw
    tags.datadoghq.com/env: Development
    tags.datadoghq.com/service: ocelotapigw
    tags.datadoghq.com/version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigw
  template:
    metadata:
      labels:
        app: ocelotapigw
        tags.datadoghq.com/env: Development
        tags.datadoghq.com/service: ocelotapigw
        tags.datadoghq.com/version: v1
    spec:
      containers:
        - name: ocelotapigw
          image: nmhieuit/ocelotapigw:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "0.5"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigw-service
spec:
  type: LoadBalancer
  selector:
    app: ocelotapigw
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 80
