apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingapi-deployment
  labels:
    app: orderingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderingapi
  template:
    metadata:
      labels:
        app: orderingapi
    spec:
      containers:
        - name: orderingapi
          image: nmhieuit/orderingapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__OrderingConnectionString
              value: "Server=orderdb-service;Database=OrderDb;User Id=sa;Password=SwN12345678"
            # - name: CacheSettings__ConnectionString
            #   valueFrom:
            #       configMapKeyRef:
            #         name: basketdb-configmap
            #         key: ConnectionString   
            - name: ElasticConfiguration
              value: "Uri=http://elasticsearch:9200"  
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: orderingapi-service
spec:
  type: LoadBalancer
  selector:
    app: orderingapi
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 80
