apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb-deployment
  labels:
    app: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                    - "small"
      containers:
        - name: orderdb
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              value: "SwN12345678"
            - name: ACCEPT_EULA
              value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: orderdb-service
spec:
  selector:
    app: orderdb
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433