apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-service
spec:
  replicas: 1
  image: rabbitmq:3-management-alpine
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi