version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://172.31.9.27:9200
    ports:
        - "5601:5601"