version: '3.4'

services:
  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ApiSettings:GatewayAddress=http://ocelotapigw"
        - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    ports:
        - "8006:80"