version: '3.4'

services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://172.31.9.27:9200
    ports:
        - "5601:5601"

    webstatus:
     container_name: webstatus
     environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
        - HealthChecksUI__HealthChecks__0__Uri=http://172.31.20.135:8000/hc
        - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
        - HealthChecksUI__HealthChecks__1__Uri=http://172.31.18.221:8001/hc
        - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
        - HealthChecksUI__HealthChecks__2__Uri=http://172.31.19.14:8002/hc
        - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
        - HealthChecksUI__HealthChecks__3__Uri=http://172.31.7.134:8004/hc
        - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
        - HealthChecksUI__HealthChecks__4__Uri=http://72.31.27.108:8005/hc
        - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
    ports:
        - "8007:80"