version: '3.4'

services:

  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://172.31.19.14:8003"
      - "EventBusSettings:HostAddress=amqp://guest:guest@172.31.27.250:5672"
      - "ElasticConfiguration:Uri=http://172.31.9.27:9200"
    depends_on:
      - basketdb
    ports:
      - "8001:80"