version: '3.4'

services:
  webstatus:
    container_name: webstatus
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
        - HealthChecksUI__HealthChecks__0__Uri=http://172.31.20.135:8000/hc
        - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
        - HealthChecksUI__HealthChecks__1__Uri=http://172.31.18.221:8001/hc
        - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
        - HealthChecksUI__HealthChecks__2__Uri=http://172.31.19.14:8002/hc
        - HealthChecksUI__HealthChecks__3__Name=Ordering Health Check
        - HealthChecksUI__HealthChecks__3__Uri=http://172.31.7.134:8004/hc
    ports:
        - "8007:80"

