version: '3.4'

services:
  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  ordering.api:
    container_name: ordering.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:OrderingConnectionString=Server=172.31.7.134;Database=OrderDb;User Id=sa;Password=SwN12345678"            
        - "EventBusSettings:HostAddress=172.31.27.250://guest:guest@rabbitmq:5672"
        - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - orderdb
    ports:
        - "8004:80"