version: '3.4'

services:
  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://172.31.9.27:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"