version: '3.4'

services:
  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://172.31.9.27:9200"
    ports:
      - "8010:80"